RACK_ENV                  = ENV['RACK_ENV']
DIGITALOCEAN_CLIENT_ID    = ENV['DIGITALOCEAN_CLIENT_ID']
DIGITALOCEAN_API_KEY      = ENV['DIGITALOCEAN_API_KEY']
OCEANMANAGER_LEADING_NAME = ENV['OCEANMANAGER_LEADING_NAME']
